version: '3.6'
services: 
    postgres:
        image: postgres
        restart: always
        # env_file:
            # - database.env
        environment: 
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=auction
        ports: 
            - "5432:5432"
        volumes:
            - database-data:/var/lib/postgresql/data/        
            # - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    
    pgadmin-compose:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: "user@domain.com"
            PGADMIN_DEFAULT_PASSWORD: "password"
        ports: 
            - "16543:80"
        depends_on: 
            - postgres    

volumes:
    database-data: